language: r
r: bioc-devel
sudo: false
cache: packages

bioc_packages: 
  - xcms 
  - msPurityData
  - covr
  - devtools
  
apt_packages:
  - libnetcdf-dev
  - netcdf-bin
  - libhdf5-dev
  
r_github_packages:
  - codecov/example-r

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O http://r.research.att.com/libs/netcdf-4.1.3-darwin9-bin3.tar.gz && sudo tar fvxz netcdf-4.1.3-darwin9-bin3.tar.gz -C /; fi

after_success:
- Rscript -e 'library(covr);codecov()'
