language: r
r: bioc-devel
sudo: false
cache: packages
warnings_are_errors: true

bioc_packages: 
  - xcms 
  - msPurityData

  
apt_packages:
  - libnetcdf-dev
  - netcdf-bin
  - libhdf5-dev
 
# Taken from XCMS travis yml created by johannes.rainer https://github.com/sneumann/xcms/blob/master/.travis.yml
jobs:
  include:
    - stage: "Build"
      r_packages:
        - covr
        - testthat
        - knitr
        - roxygen2
      before_install:
        - mkdir -p ~/.R
        - echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
        - echo 'options(Ncpus = 2)' > ~/.Rprofile
        - echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' > ~/.Rprofile
        - echo 'utils::chooseCRANmirror(ind = 1)' > ~/.Rprofile
      script: true
      name: "Build dependencies and cache"
    - stage: "Check"
      r_build_args: --no-build-vignettes --no-manual
      r_check_args: --as-cran --no-build-vignettes --no-vignettes --no-manual --no-tests
      before_script: rm -rf vignettes
      install: skip
      name: "examples"
    - r_build_args: --no-build-vignettes --no-manual
      r_check_args: --as-cran --no-build-vignettes --no-vignettes --no-manual --no-codoc --no-examples
      install: skip
      before_script: rm -rf vignettes
      name: "tests"
    - r_build_args:
      r_check_args: --as-cran --no-build-vignettes --no-codoc --no-examples --no-tests
      install: skip
      name: "vignettes"
    - stage: "CodeCov"
      install: skip
      script:
        - travis_wait 20 Rscript -e 'covr::codecov()'
      name: "codecov and pkgdown (on master)"

# In general the r-travis script automatically dump the logs after failure but
# because of a bug in travis the output is often truncated. See
# https://github.com/travis-ci/travis-ci/issues/6018
after_failure: sleep 10


before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O http://r.research.att.com/libs/netcdf-4.1.3-darwin9-bin3.tar.gz && sudo tar fvxz netcdf-4.1.3-darwin9-bin3.tar.gz -C /; fi


