language: r
cache: packages
r: bioc-stable
os:
  - linux


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdf-dev texlive-latex-base; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O http://r.research.att.com/libs/netcdf-4.1.3-darwin9-bin3.tar.gz && sudo tar fvxz netcdf-4.1.3-darwin9-bin3.tar.gz -C /; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://bioconductor.org/packages/devel/data/experiment/src/contrib/msPurityData_0.99.0.tar.gz -o msPurityData_0.99.0.tar.gz && R CMD INSTALL msPurityData_0.99.0.tar.gz; fi
