language: r
r: bioc-devel
sudo: required
cache: packages
r_packages:
  - knitr
  - XML
  - devtools
bioc_packages: 
  - xcms 
  - Rgraphviz
  - msPurityData
apt_packages:
  - texlive-latex-extra
  - texlive-fonts-extra
  - texlive-latex-recommended
  - libnetcdf-dev
  - netcdf-bin
  - libhdf5-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O http://r.research.att.com/libs/netcdf-4.1.3-darwin9-bin3.tar.gz && sudo tar fvxz netcdf-4.1.3-darwin9-bin3.tar.gz -C /; fi
