language: r
cache: packages
r: bioc-devel
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnetcdf-dev texlive-latex-base; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O http://r.research.att.com/libs/netcdf-4.1.3-darwin9-bin3.tar.gz; sudo tar fvxz netcdf-4.1.3-darwin9-bin3.tar.gz -C; fi
